-- AlterTable
ALTER TABLE "Company" ADD COLUMN     "stockUnits" DECIMAL(12,2) NOT NULL DEFAULT 0,
ADD COLUMN     "unitPrice" DECIMAL(10,2) NOT NULL DEFAULT 12;

-- AlterTable
ALTER TABLE "CompanyCycleReport" ADD COLUMN     "stockUnits" DECIMAL(12,2) NOT NULL DEFAULT 0,
ADD COLUMN     "unitCost" DECIMAL(10,2) NOT NULL DEFAULT 0,
ADD COLUMN     "unitPrice" DECIMAL(10,2) NOT NULL DEFAULT 0,
ADD COLUMN     "unitsLost" DECIMAL(12,2) NOT NULL DEFAULT 0,
ADD COLUMN     "unitsProduced" DECIMAL(12,2) NOT NULL DEFAULT 0,
ADD COLUMN     "unitsSold" DECIMAL(12,2) NOT NULL DEFAULT 0;
